# Generated by Django 5.1 on 2024-09-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtracking',
            old_name='Subscriber',
            new_name='subscriber',
        ),
    ]
