# Generated by Django 5.1 on 2024-09-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='exchange',
            new_name='Exchange',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='sector',
            new_name='Sector',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='symbol',
            new_name='Symbol',
        ),
    ]
